// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using news_feed_reader.Models;

namespace newsfeedreader.Migrations
{
    [DbContext(typeof(NewsFeedContext))]
    [Migration("20180622082255_RemoveSubscriptionTable")]
    partial class RemoveSubscriptionTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("news_feed_reader.Models.NewsFeedProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogoURL");

                    b.Property<string>("Name");

                    b.Property<string>("RssFeedURL");

                    b.Property<string>("WebsiteURL");

                    b.Property<bool>("isSubscribed");

                    b.HasKey("Id");

                    b.ToTable("NewsFeedProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
